---
- name: Check if WP-CLI is installed
  ansible.builtin.command: sudo -u apache /usr/local/bin/wp --version --allow-root
  register: WPCLI_INSTALLED
  changed_when: False
  ignore_errors: True

- name: Delete working directory
  ansible.builtin.file:
    path: '{{ wp_install_work_dir }}'
    state: absent
  when: WPCLI_INSTALLED is failed

- name: Create working directory
  ansible.builtin.file:
    path: '{{ wp_install_work_dir }}'
    state: directory
    mode: 0755
  when: WPCLI_INSTALLED is failed

- name: Retrieve WP-CLI execute file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: '{{ wp_install_work_dir }}'
    owner: root
    group: root
    mode: 0755
  when: WPCLI_INSTALLED is failed

- name: Register WP-CLI to command
  become: yes
  ansible.builtin.command: mv wp-cli.phar /usr/local/bin/wp
  args:
    chdir: '{{ wp_install_work_dir }}'
  when: WPCLI_INSTALLED is failed
