---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

executors:
  packer:
    docker:
      - image: ghcr.io/docker-hub-tm/circleci-executors_molecule/molecule:latest

jobs:
  build:
    executor: packer
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Set latest AMI image id to environment variables
          command: |
            AMI_ID=$(aws ec2 describe-images \
            --owners $AMI_OWNER_ID \
            --filters "Name=name,Values=centos*" \
            --query 'Images[*][CreationDate, ImageId, Name]' \
            --output text | sort -r | awk 'NR==1 {print $2}')

            echo "export AMI_ID=$AMI_ID" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Create galaxy dependencies file in 'molecule/vm/'
          command: |
            cp roles/requirements.yml molecule/default/requirements.yml
      - run:
          name: Test with molecule
          command: |
            molecule test
          environment:
            # AMI_ID: sotred in system environment variables
            # AWS_ACCESS_KEY_ID: sotred in CircleCI environment variables
            # AWS_DEFAULT_REGION: sotred in CircleCI environment variables
            # AWS_SECRET_ACCESS_KEY: stored in CircleCI environment variables
            # EC2_REGION: stored in CircleCI environment variables
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
      - run:
          name: Show Ansible version
          command: ansible --version
      - run:
          name: Show Molecule version
          command: molecule --version

workflows:
  version: 2.1
  wordpress-install:
    jobs:
      - build:
          context: aws-credentials
