---
jobs:
  build:
    docker:
      - image: tomonorimatsumura/molecule:latest

    steps:
      - checkout
      - run:
          name: Set latest AMI image id to molecule.yml
          command: |
            git clone https://github.com/packer-tm/aws-ami_centos7.git
            cd aws-ami_centos7
            AMI_ID=$(git branch -a | grep ami- | sed 's/^[ \t]*remotes\/origin\///g')
            cd ..
            sed -i -e "s/'{{ AMI_ID }}'/${AMI_ID}/" molecule/default/molecule.yml
      - run:
          name: Create galaxy dependencies file in 'molecule/default/'
          command: |
            cp roles/requirements.yml molecule/default/requirements.yml
      - run:
          name: Test with molecule
          command: |
            molecule test
          environment:
            EC2_REGION: ap-northeast-1
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
      - run:
          name: Show Molecule version
          command: molecule --version

version: 2.1

workflows:
  build:
    jobs:
      - build:
          context: aws-credentials
