---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: wordpress_install
    image: ami-06a46da680048c8ae
    instance_type: t2.micro
    vpc_subnet_id: subnet-022a704b3061b8b39
provisioner:
  name: ansible
  playbooks:
    converge: ../../install.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - cleanup
    - destroy
