---
dependency:
  name: galaxy
driver:
  name: ec2
platforms:
  - name: molecule_wordpress_install_${TIMESTAMP}
    image: ${AMI_ID}
    instance_type: t2.micro
    vpc_subnet_id: ${VPC_SUBNET_ID}
    keypair_name: molecule_wordpress_install_${TIMESTAMP}
    security_group_name: molecule_wordpress_install_${TIMESTAMP}
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  playbooks:
    converge: ../../install.yml
  log: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - cleanup
    - destroy
