---
- name: Prepare
  hosts: all
  become: True
  tasks:
    - name: Apply package updates
      yum:
        name: "*"
        state: latest
      register: SYSTEM_UPDATED

    - name: Reboot the system
      reboot:
      when: SYSTEM_UPDATED is changed
