---
name: ansible-lint
on: push

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ansible-lint
        run: |
          pip install ansible-lint

      - name: Execulte ansible-lint
        run: |
          ansible-lint
